apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: ingress-nginx
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: jduarte104/train-schedule:latest
        ports:
        - containerPort: 5000
